# Generated by Django 4.2.1 on 2023-05-10 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0003_empresa_rename_fecha_inmueble_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Inmueble', to='inmuebleslist_app.empresa'),
            preserve_default=False,
        ),
    ]
