# Generated by Django 4.2.1 on 2023-05-10 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0005_alter_inmueble_empresa_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='efificacion',
            new_name='inmueble',
        ),
    ]
